language: go

sudo: false

go:
  - 1.6
  - 1.7
  - tip

before_script:
  - go fmt ./...
  - go vet $(go list ./...)

script:
  - go test -coverprofile=coverage.txt -covermode=atomic ./function/
  - go test ./function/ -bench=. -cpu=1,2,4,8

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - kevingo75@gmail.com
